In [2]:
'''Write some code to generate a 1D array of 1000 evenly spaced numbers from 0 to 2π. Then create a second
array where each value in the array is double that of the previous array (call these x1 and x2 respectively)'''

'Write some code to generate a 1D array of 1000 evenly spaced numbers from 0 to 2π. Then create a second\narray where each value in the array is double that of the previous array (call these x1 and x2 respectively)'

In [3]:
import numpy as np

In [4]:
arr=np.array([])
x1=np.arange(0, 2*np.pi, 2*np.pi/1000)
# alternatively, x1=np.linspace(0, 2*np.pi, 1000)
x2=2*x1
x1

array([0.        , 0.00628319, 0.01256637, 0.01884956, 0.02513274,
       0.03141593, 0.03769911, 0.0439823 , 0.05026548, 0.05654867,
       0.06283185, 0.06911504, 0.07539822, 0.08168141, 0.08796459,
       0.09424778, 0.10053096, 0.10681415, 0.11309734, 0.11938052,
       0.12566371, 0.13194689, 0.13823008, 0.14451326, 0.15079645,
       0.15707963, 0.16336282, 0.169646  , 0.17592919, 0.18221237,
       0.18849556, 0.19477874, 0.20106193, 0.20734512, 0.2136283 ,
       0.21991149, 0.22619467, 0.23247786, 0.23876104, 0.24504423,
       0.25132741, 0.2576106 , 0.26389378, 0.27017697, 0.27646015,
       0.28274334, 0.28902652, 0.29530971, 0.30159289, 0.30787608,
       0.31415927, 0.32044245, 0.32672564, 0.33300882, 0.33929201,
       0.34557519, 0.35185838, 0.35814156, 0.36442475, 0.37070793,
       0.37699112, 0.3832743 , 0.38955749, 0.39584067, 0.40212386,
       0.40840704, 0.41469023, 0.42097342, 0.4272566 , 0.43353979,
       0.43982297, 0.44610616, 0.45238934, 0.45867253, 0.46495

In [5]:
'''Take the mean, median, and standard deviation of x1 and x2 using NumPy.'''
np.mean(x1)
np.median(x1)
np.std(x1)

1.8137984573343091

In [6]:
'''Create an array of 100 numbers using np.linspace or np.arange from 0 to 100. Use boolean filtering to
create new arrays from the one we just created that satisfy the following criteria:
• Only even numbers.
• Only odd numbers that are divisible by 7.
• Numbers divisible by 10 and divisible by 5.
• Numbers that are greater than 42.
• Only numbers that are multiples of 2,3, and 5.
'''
filtered=np.arange(101)
evens=filtered[filtered%2==0]

In [7]:
evens

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [18]:
import sys
frequency=np.linspace(10, 50000, 7)
np.set_printoptions(threshold=sys.maxsize)

In [19]:
frequency

array([1.00000000e+01, 8.34166667e+03, 1.66733333e+04, 2.50050000e+04,
       3.33366667e+04, 4.16683333e+04, 5.00000000e+04])

In [23]:
for i in frequency:
    print(i)

10.0
8341.666666666666
16673.333333333332
25005.0
33336.666666666664
41668.33333333333
50000.0
