# Lab 6 - Weighted Linear Fit
## *based on the lab 6 excel file
Zhirong Zhang (zhirongz@berkeley.edu)

In [85]:
import numpy as np
import scipy.optimize as opt
import matplotlib.pyplot as plt

## Preparation of Data
In this part, we first read in the data. Then we calculate the means and standard errors.

In [86]:
#Read in data from the csv file
data_table = np.loadtxt('lab6_test_dataset_csv.csv', delimiter=',', skiprows=1)

#allocate a numpy matrix for storing periods
time_table = np.zeros((9,7))

#Sort the data into the time_table
for n in list(range(1,10)):
    time_table[n-1] = data_table[:,n]

In [87]:
#mean
#axis = 1 meaning we are average each row
mean = np.mean(time_table, axis=1)
print('mean :')
print(mean)

#standard deviation
std = np.std(time_table, axis=1, ddof=1)
print('standard deviation :')
print(std)

#standard error
stderr = std/np.sqrt(7)
print('standard error')
print(stderr)

mean :
[ 4.77285714  6.44285714  7.50142857  8.47714286  9.57142857 10.39428571
 11.38142857 11.99142857 12.62428571]
standard deviation :
[0.03817254 0.06129554 0.06094494 0.11513967 0.05639993 0.07678045
 0.09546877 0.04488079 0.08676734]
standard error
[0.01442786 0.02316754 0.02303502 0.0435187  0.02131717 0.02902028
 0.0360838  0.01696335 0.03279497]


## Continue preparing data ...
Now we compute the time for each rotational period, and propagate the errors.

In [88]:
T = mean/10
alpha_T = stderr/10
T_square = np.square(T)
alpha_T_square = 2*np.multiply(T,alpha_T)

Time to move on to moment of inertia.

In [89]:
#Prepare some constant.
#LOAD YOUR OWN CONSTANTS!

#Moment of inertia of the holder
I_HOLDER = 100
#Moment of inertia of a single disk
I_DISK = 286.8

#construct moment of inertia error
n_array = np.arange(1,10)
I_array = I_HOLDER+I_DISK*n_array

Error propagation. Fun stuff!

In [90]:
alpha_holder = 3.2
alpha_disk = 6.6

alpha_I = np.sqrt(np.square(alpha_holder)+np.square(n_array)*np.square(alpha_disk))

## Non-weighted Fit

In [91]:
def model_lin(x, m, c):
    return m*x

In [92]:
lin_opt, lin_cov = opt.curve_fit(model_lin, T_square, I_array)

## Weighted-Fit

In [93]:
alpha_I0 = lin_opt[0]*alpha_T_square

In [94]:
#The error of x is added to the error of y.
alpha_I_eq = np.sqrt(np.square(alpha_I)+np.square(alpha_I0))

In [95]:
w = 1/np.square(alpha_I_eq)

In [97]:
wx = np.multiply(T_square,w)

In [99]:
wxy = np.multiply(wx,I_array)

array([1.49101394, 1.33553211, 1.24057389, 1.04312137, 1.2265729 ,
       1.17094009, 1.17018637, 1.21049717, 1.14558738])

In [100]:
sqrt_w = np.sqrt(w)

In [102]:
x2 = np.square(T_square)
x2w = np.multiply(x2,w)

array([0.00087812, 0.00082302, 0.00072687, 0.00060103, 0.00073252,
       0.0006948 , 0.00071922, 0.00072696, 0.00068095])

In [104]:
xw = np.multiply(w, T_square)

array([0.00385474, 0.00198268, 0.00129173, 0.00083637, 0.00079959,
       0.00064309, 0.00055522, 0.00050555, 0.00042727])

In [105]:
wy = np.multiply(w, I_array)

In [121]:
weighted_m = (np.sum(w)*np.sum(wxy)-np.sum(xw)*np.sum(wy))/(np.sum(w)*np.sum(x2w)-np.sum(xw)**2)

In [123]:
print(weighted_m)

1668.6057191881198
