In [1]:
'''1 Hey Twin
Given an array, find the rows where all the values are equal.
>>> a r r = np . a r r a y ( [ [ 1 , 1 , 1 ] , [ 1 , 2 , 3 ] , [ 2 , 2 , 2 ] ] )
>>> f i n d E q u a l ( a r r )
a r r a y ( [ [ 1 , 1 , 1 ] ,
[ 2 , 2 , 2 ] ] )'''

'1 Hey Twin\nGiven an array, find the rows where all the values are equal.\n>>> a r r = np . a r r a y ( [ [ 1 , 1 , 1 ] , [ 1 , 2 , 3 ] , [ 2 , 2 , 2 ] ] )\n>>> f i n d E q u a l ( a r r )\na r r a y ( [ [ 1 , 1 , 1 ] ,\n[ 2 , 2 , 2 ] ] )'

In [2]:
import numpy as np

In [8]:
def findEqual(a):
    b = np.array([],dtype=int)
    for i in range(a.shape[0]):
        if all(x == a[i][0] for x in a[i]):
            b = np.append(b, a[i])
    return b.reshape(-1,a.shape[1])

arr = np.array([[1,1,1],[1,2,3],[2,2,2]])
print(arr)
print(findEqual(arr))

[[1 1 1]
 [1 2 3]
 [2 2 2]]
[[1 1 1]
 [2 2 2]]
