In [2]:
'''4 Everything is in order
Given a multidimensional matrix, sort the matrix along the columns.
>>> np . random . s e e d ( 1 2 3 4 5 )
>>> a = np . random . r a n d i n t ( 1 , 5 0 , ( 4 , 5 ) )
>>> a
a r r a y ( [ [ 3 5 , 3 8 , 3 0 , 2 , 3 7 ] ,
[ 4 2 , 3 8 , 3 5 , 3 0 , 2 ] ,
[ 1 5 , 4 2 , 2 8 , 1 7 , 1 0 ] ,
[ 1 2 , 1 4 , 1 1 , 1 8 , 1 9 ] ] )
>>> s o r t i n g ( a )
a r r a y ( [ [ 1 2 , 1 4 , 1 1 , 2 , 2 ] ,
[ 1 5 , 3 8 , 2 8 , 1 7 , 1 0 ] ,
[ 3 5 , 3 8 , 3 0 , 1 8 , 1 9 ] ,
[ 4 2 , 4 2 , 3 5 , 3 0 , 3 7 ] ] '''

'4 Everything is in order\nGiven a multidimensional matrix, sort the matrix along the columns.\n>>> np . random . s e e d ( 1 2 3 4 5 )\n>>> a = np . random . r a n d i n t ( 1 , 5 0 , ( 4 , 5 ) )\n>>> a\na r r a y ( [ [ 3 5 , 3 8 , 3 0 , 2 , 3 7 ] ,\n[ 4 2 , 3 8 , 3 5 , 3 0 , 2 ] ,\n[ 1 5 , 4 2 , 2 8 , 1 7 , 1 0 ] ,\n[ 1 2 , 1 4 , 1 1 , 1 8 , 1 9 ] ] )\n>>> s o r t i n g ( a )\na r r a y ( [ [ 1 2 , 1 4 , 1 1 , 2 , 2 ] ,\n[ 1 5 , 3 8 , 2 8 , 1 7 , 1 0 ] ,\n[ 3 5 , 3 8 , 3 0 , 1 8 , 1 9 ] ,\n[ 4 2 , 4 2 , 3 5 , 3 0 , 3 7 ] ] '

In [3]:
import numpy as np

def sorting(arr=np.array([[]])):
    arr=np.sort(arr)
    return arr
sorting(a)

In [4]:
np.random.seed(12345)
a=np.random.randint(1, 50, (4,5))
a

array([[35, 38, 30,  2, 37],
       [42, 38, 35, 30,  2],
       [15, 42, 28, 17, 10],
       [12, 14, 11, 18, 19]])

In [5]:
def sorting(a=np.array([])):
    for i in range(0, len(a[0])):
    print(a)
    return a
sorting(a)

IndentationError: expected an indented block after 'for' statement on line 2 (3768285582.py, line 3)

In [11]:
def sortArray(a):
    b = np.sort(a, axis=0)
    return b
print(a)
sortArray(a)

[[35 38 30  2 37]
 [42 38 35 30  2]
 [15 42 28 17 10]
 [12 14 11 18 19]]


array([[12, 14, 11,  2,  2],
       [15, 38, 28, 17, 10],
       [35, 38, 30, 18, 19],
       [42, 42, 35, 30, 37]])